controllers:
    resource: ../src/Controller/
    type: attribute
#app_lucky_pozdrav:
#    path: /lucky/pozdrav
#    controller: App\Controller\PozdravController::pozdrav

# config/routes/annotations.yaml

